### ISSUE TITLE
Implementing selmer in pedestal

### ISSUE THREAD

**Issue by suresanand89** [csula/cs590-fall-2015#15]
Can you show us how to implement selmer in pedestal.io?

**Comment by john-csula** [comment]
@suresanand89 thanks so much for posting your question.  How about this?
- Update your `project.clj` by adding following to your `:dependencies`

``` clojure
[selmer "0.9.5"]
[markdown-clj "0.9.80"]
[environ "1.0.1"]
[metosin/ring-middleware-format "0.6.0"]
[metosin/ring-http-response "0.6.5"]
[ring/ring-defaults "0.1.5"]
```
- Create a file called `layout.clj` with the contents from [`layout.clj`](https://github.com/csula/cs590-fall-2015/blob/master/src/lms-gradesheet/src/lms_gradesheet/layout.clj)
- Modify your `service.clj`
  - Add`[gradesheet.layout :as layout]` to `:require`
  - Add a route `/selmer` and its function `(defn selmer-page [request] (layout/render "example.html"))`
- Create contents for `resources/templates/example.html`
